language: ruby
cache: bundler
env:
- SERVER_IP_ADDRESS=dev.moysklad.ru APP_PREFIX=api-loyalty
branches:
  only:
  - DO-720
script:
- bundle install
- bundle exec middleman build --build-dir=site
deploy:
  provider: script
  skip_cleanup: true
  script: rsync --list-only app@${SERVER_IP_ADDRESS}:./${APP_PREFIX}
  #-r --delete-after --quiet site/
  on:
    branch: DO-720
before_install:
- openssl aes-256-cbc -K $encrypted_687158784e62_key -iv $encrypted_687158784e62_iv
  -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host ${SERVER_IP_ADDRESS}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key app@${SERVER_IP_ADDRESS} pwd
- rm deploy_key.enc deploy_key
